apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: self-hosted-runners
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: raftriani/python-app
      labels:
        - self-hosted
      env:
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi