redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd.test.com

configs:
  params:
    server.insecure: false
    server.grpc.web: true

certificate:
  enabled: true

server:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.test.com
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.test.com